version: "2"
services:
    db:
        container_name: mongodb
        image: mongo
        expose:
            - "27017"
    web:
        container_name: adcweb
        build: .
        ports:
            - "3000:3000"
        links:
            - db
