version: "2"
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
    web:
        build: .
        ports:
            - "3000:3000"
        links:
            - db
        depends_on:
            - db
